SET @ROWNUM := -1;

SELECT HOUR, COUNT
FROM ((
    SELECT cast(DATE_FORMAT(DATETIME, '%H') as unsigned) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY DATE_FORMAT(DATETIME, '%H')
    ORDER BY HOUR
)
UNION (
    SELECT cast((@ROWNUM := @ROWNUM + 1) as unsigned) HOUR, 0
    FROM ANIMAL_OUTS
    WHERE @ROWNUM < 23
)) A
GROUP BY HOUR
ORDER BY HOUR