SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R
INNER JOIN (
    SELECT MEMBER_NAME, I.MEMBER_ID, COUNT(I.MEMBER_ID) CNT
    FROM MEMBER_PROFILE I
        LEFT OUTER JOIN REST_REVIEW R
        ON I.MEMBER_ID = R.MEMBER_ID
    GROUP BY I.MEMBER_ID
    HAVING CNT = (
        SELECT COUNT(I.MEMBER_ID) CNT
        FROM MEMBER_PROFILE I
        LEFT OUTER JOIN REST_REVIEW R
        ON I.MEMBER_ID = R.MEMBER_ID
        GROUP BY I.MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    )
) J ON R.MEMBER_ID = J.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT